window.FLIGHT_DATA = {
  passengers: [
    { surname: "NG", given: "YI HIN", gender: "M" },
    { surname: "NG", given: "YI HO", gender: "M" },
    { surname: "NG", given: "SUM YU", gender: "F" },
    { surname: "CHUNG", given: "WING TUNG", gender: "F" },
    { surname: "YING", given: "HEI TUNG", gender: "F" },
  ],
  flights: [
    {
      id: "f1",
      date: "2026-08-01",
      dateLabel: { zh: "8月1日 · 六", en: "Sat · Aug 1" },
      airline: { zh: "香港快運", en: "HK Express" },
      flightNo: "UO604",
      pnr: "H53ETV",
      fareClass: "Q",
      cabin: { zh: "經濟飛", en: "Economy" },
      from: { code: "HKG", zh: "香港國際機場 T2", en: "Hong Kong Int'l T2" },
      to: { code: "PUS", zh: "金海國際機場", en: "Gimhae Int'l" },
      depart: "02:35",
      arrive: "07:00",
      checkInHint: { zh: "建議 23:30 前到機場（起飛前約 3 小時）", en: "Arrive by ~23:30 (≈3 hrs before departure)" },
      bagCarry: { zh: "隨身物品 + 登機行李（共 ≤7kg）", en: "Personal item + cabin bag (≤7kg total)" },
      seats: [
        { name: "YI HIN NG", seat: "17B", bag: null },
        { name: "YI HO NG", seat: "17D", bag: null },
        { name: "SUM YU NG", seat: "17E", bag: "20kg" },
        { name: "WING TUNG CHUNG", seat: "17F", bag: "20kg" },
        { name: "HEI TUNG YING", seat: "17A", bag: "20kg" },
      ],
    },
    {
      id: "f2",
      date: "2026-08-04",
      dateLabel: { zh: "8月4日 · 二", en: "Tue · Aug 4" },
      airline: { zh: "濟州航空", en: "Jeju Air" },
      flightNo: "7C0503",
      pnr: "ITLPKA260613SXNI3065",
      fareClass: null,
      cabin: { zh: "經濟艙", en: "Economy" },
      from: { code: "PUS", zh: "金海國際機場", en: "Gimhae Int'l" },
      to: { code: "CJU", zh: "濟州國際機場", en: "Jeju Int'l" },
      depart: "08:50",
      arrive: "09:55",
      checkInHint: { zh: "建議 06:50 前到機場（國內線約 2 小時）· 酒店約 06:00 出發", en: "Arrive by ~06:50 (≈2 hrs for domestic) · leave hotel ~06:00" },
      bagCarry: { zh: "隨身+手提共 ≤10kg · 托運每人 ≤30kg", en: "Carry-on ≤10kg total · checked ≤30kg each" },
      seats: [
        { name: "NG SUM YU", seat: "—", bag: "shared rule" },
        { name: "CHUNG WING TUNG", seat: "—", bag: "shared rule" },
        { name: "NG YI HO", seat: "—", bag: "shared rule" },
        { name: "NG YI HIN", seat: "—", bag: "shared rule" },
        { name: "YING HEI TUNG", seat: "—", bag: "shared rule" },
      ],
    },
    {
      id: "f3",
      date: "2026-08-07",
      dateLabel: { zh: "8月7日 · 五", en: "Fri · Aug 7" },
      airline: { zh: "香港快運", en: "HK Express" },
      flightNo: "UO699",
      pnr: "EBZT9A",
      fareClass: "V",
      cabin: { zh: "經濟飛", en: "Economy" },
      from: { code: "CJU", zh: "濟州國際機場", en: "Jeju Int'l" },
      to: { code: "HKG", zh: "香港國際機場 T1", en: "Hong Kong Int'l T1" },
      depart: "07:30",
      arrive: "09:40",
      checkInHint: { zh: "建議 05:00 前到機場 · 酒店約 04:45–05:00 出發", en: "Arrive by ~05:00 · leave hotel ~04:45–05:00" },
      bagCarry: { zh: "隨身物品 + 登機行李（共 ≤7kg）", en: "Personal item + cabin bag (≤7kg total)" },
      seats: [
        { name: "YI HIN NG", seat: "14B", bag: null },
        { name: "YI HO NG", seat: "14E", bag: null },
        { name: "SUM YU NG", seat: "14D", bag: "20kg" },
        { name: "WING TUNG CHUNG", seat: "14F", bag: "20kg" },
        { name: "HEI TUNG YING", seat: "14A", bag: "20kg" },
      ],
    },
  ],
};
