window.FOOD_DATA = {
  title: { zh: "濟州美食 List", en: "Jeju Food List" },
  hint: {
    zh: "旅途彈性備選 · 點地址可開 Google Maps · ★ 已排進行程",
    en: "Flexible picks · tap address for Maps · ★ already on itinerary",
  },
  places: [
    {
      id: "mochiron",
      name: { zh: "mochiron", en: "mochiron" },
      nameKo: "모치론",
      category: { zh: "餐廳", en: "Restaurant" },
      area: { zh: "濟州市 · 觀德", en: "Jeju-si · Gwandeok" },
      address: "10 Gwandeok-ro 6-gil, Jeju-si",
      note: null,
      maps: "10 Gwandeok-ro 6-gil, Jeju-si",
      dayHint: null,
    },
    {
      id: "haenyeo-bread",
      name: { zh: "海女麵包", en: "Haenyeo Bread" },
      nameKo: "해녀의부엌 / 해녀빵",
      category: { zh: "麵包", en: "Bakery" },
      area: { zh: "涯月", en: "Aewol" },
      address: "24-9 Aewol-ro 1-gil, Aewol-eup, Jeju-si",
      note: null,
      maps: "24-9 Aewol-ro 1-gil, Aewol-eup, Jeju-si",
      dayHint: { zh: "適合 Day 3 涯月線", en: "Fits Day 3 Aewol leg" },
    },
    {
      id: "byronic",
      name: { zh: "byronic", en: "byronic" },
      nameKo: "바이로닉",
      category: { zh: "咖啡 / 餐廳", en: "Café / Restaurant" },
      area: { zh: "涯月海岸", en: "Aewol coast" },
      address: "96 Teuhaean-ro, Aewol-eup, Jeju-si",
      note: null,
      maps: "96 Teuhaean-ro, Aewol-eup, Jeju-si",
      dayHint: { zh: "適合 Day 3 涯月線", en: "Fits Day 3 Aewol leg" },
    },
    {
      id: "solla",
      name: { zh: "濟州大排檔（小 LA）", en: "Jeju Food Stall (Little LA)" },
      nameKo: "제주대포 / 소라",
      category: { zh: "宵夜 / 排檔", en: "Night market style" },
      area: { zh: "濟州市 · 建入洞", en: "Jeju-si · Geonip" },
      address: "13 Jungang-ro, Geonip-dong, Jeju-si",
      note: null,
      maps: "13 Jungang-ro, Geonip-dong, Jeju-si",
      dayHint: null,
    },
    {
      id: "cheetah-chicken",
      name: { zh: "치타치킨（大推！）", en: "Cheetah Chicken (must-try)" },
      nameKo: "치타치킨",
      category: { zh: "炸雞", en: "Fried chicken" },
      area: { zh: "濟州市 · 新光路", en: "Jeju-si · Singwang" },
      address: "제주 제주시 신광로4길 7",
      note: { zh: "原 list 大推 · 超好吃", en: "Highly recommended on the list" },
      maps: "신광로4길 7, Jeju-si",
      dayHint: { zh: "可替代 / 加點蓮洞晚餐", en: "Alt / add-on for Yeondong dinner" },
    },
    {
      id: "slowboat",
      name: { zh: "Slowboat", en: "Slowboat" },
      nameKo: "슬로우보트",
      category: { zh: "海景咖啡", en: "Ocean café" },
      area: { zh: "涯月 · 下貴", en: "Aewol · Hagwi" },
      address: "제주 제주시 애월읍 하귀2길 46-16",
      note: { zh: "整棟兩層面海 · 一樓二樓大橫窗", en: "2 floors facing the sea · big windows" },
      maps: "하귀2길 46-16, Aewol-eup, Jeju-si",
      dayHint: { zh: "適合 Day 3 涯月線", en: "Fits Day 3 Aewol leg" },
    },
    {
      id: "landing-coffee",
      name: { zh: "landing coffee", en: "landing coffee" },
      nameKo: "랜딩커피",
      category: { zh: "海景咖啡", en: "Ocean café" },
      area: { zh: "城山 / 西歸浦", en: "Seongsan / Seogwipo" },
      address: "45-1 Sinyang-ro 122beon-gil, Seongsan-eup, Seogwipo-si",
      note: { zh: "落地玻璃看海", en: "Floor-to-ceiling ocean views" },
      maps: "45-1 Sinyang-ro 122beon-gil, Seongsan-eup, Seogwipo-si",
      dayHint: { zh: "適合 Day 2 城山線", en: "Fits Day 2 Seongsan leg" },
    },
    {
      id: "cafe-mur",
      name: { zh: "cafe mur", en: "cafe mur" },
      nameKo: "카페 므르",
      category: { zh: "法式田園咖啡", en: "French garden café" },
      area: { zh: "西歸浦", en: "Seogwipo" },
      address: "제주 서귀포시 하엄로 28",
      note: { zh: "浪漫田園氣息", en: "Romantic countryside vibe" },
      maps: "하엄로 28, Seogwipo-si",
      dayHint: null,
    },
    {
      id: "lazy-pump",
      name: { zh: "lazy pump", en: "lazy pump" },
      nameKo: "레이지펌프",
      category: { zh: "海景咖啡", en: "Ocean café" },
      area: { zh: "涯月", en: "Aewol" },
      address: "제주특별자치도 제주시 애월읍 애월리 2578-5",
      note: { zh: "三樓陽光房必去", en: "3F sunroom is a must" },
      maps: "애월리 2578-5, Aewol-eup, Jeju-si",
      dayHint: { zh: "適合 Day 3 涯月線", en: "Fits Day 3 Aewol leg" },
    },
    {
      id: "haejigae",
      name: { zh: "Haejigae Cafe（海止開）", en: "Haejigae Café" },
      nameKo: "해지개",
      category: { zh: "海景烘焙咖啡", en: "Ocean bakery café" },
      area: { zh: "涯月 · 漢潭", en: "Aewol · Handam" },
      address: "제주 제주시 애월읍 애월북서길 52",
      note: { zh: "漢潭海景通窗 · 烘焙 · 可順散步路", en: "Handam ocean windows · bakery · coast walk nearby" },
      maps: "애월북서길 52, Aewol-eup, Jeju-si",
      dayHint: { zh: "★ 實況 Day 3（9.81 後）", en: "★ Actual Day 3 (after 9.81)" },
      onItinerary: true,
    },
    {
      id: "mou-moon",
      name: { zh: "mou moon", en: "mou moon" },
      nameKo: "머문카페",
      category: { zh: "海景咖啡", en: "Ocean café" },
      area: { zh: "舊左 / 月汀", en: "Gujwa / Woljeong" },
      address: "제주 제주시 구좌읍 해맞이해안로 460 2층",
      note: { zh: "風景很美 · 簡約時尚", en: "Great views · simple stylish interior" },
      maps: "해맞이해안로 460, Gujwa-eup, Jeju-si",
      dayHint: { zh: "Day 3 未去", en: "Not visited Day 3" },
    },
    {
      id: "rest-cafe",
      name: { zh: "休止符咖啡廳", en: "Rest Café (휴지부)" },
      nameKo: "휴지부",
      category: { zh: "網美咖啡", en: "Photo café" },
      area: { zh: "翰林", en: "Hallim" },
      address: "제주시 한림읍 한림로 359",
      note: { zh: "一樓落地窗 · 二樓秋千 · 三樓吊床", en: "Windows / swing / hammock photo spots" },
      maps: "한림로 359, Hallim-eup, Jeju-si",
      dayHint: null,
    },
    {
      id: "cafe-layered",
      name: { zh: "小狗咖啡（Cafe Layered）", en: "Cafe Layered (puppy café)" },
      nameKo: "카페 레이어드",
      category: { zh: "主題咖啡", en: "Theme café" },
      area: { zh: "舊左 · 東福", en: "Gujwa · Dongbok" },
      address: "제주 제주시 구좌읍 동복로 85 주1동 1층",
      note: { zh: "Ins 風 · 小狗周邊很多", en: "IG vibe · lots of puppy merch" },
      maps: "동복로 85, Gujwa-eup, Jeju-si",
      dayHint: { zh: "Day 3 未去", en: "Not visited Day 3" },
    },
    {
      id: "moalboal-gujwa",
      name: { zh: "Moalboal Cafe（舊左）", en: "Moalboal Café (Gujwa)" },
      nameKo: "모알보알",
      category: { zh: "波西米亞咖啡", en: "Boho café" },
      area: { zh: "舊左海岸", en: "Gujwa coast" },
      address: "구좌읍 구좌해안로 141",
      note: { zh: "彩色吊燈 · 海邊床/鋼琴/浴缸超好拍", en: "Colorful lamps · beach bed/piano/tub" },
      maps: "구좌해안로 141, Gujwa-eup, Jeju-si",
      dayHint: { zh: "適合 Day 3 東線咖啡", en: "Fits Day 3 east cafés" },
    },
    {
      id: "team-blow",
      name: { zh: "team blow", en: "team blow" },
      nameKo: "팀블로우",
      category: { zh: "海景咖啡", en: "Ocean café" },
      area: { zh: "涯月", en: "Aewol" },
      address: "제주 제주시 애월읍 애월로 19-5",
      note: { zh: "店內大片玻璃窗看海", en: "Huge glass windows to the sea" },
      maps: "애월로 19-5, Aewol-eup, Jeju-si",
      dayHint: { zh: "適合 Day 3 涯月線", en: "Fits Day 3 Aewol leg" },
    },
    {
      id: "alice-matcha",
      name: { zh: "抹茶冰 · Alice 蓮洞店", en: "Matcha ice · Alice Yeondong" },
      nameKo: "앨리스 연동점",
      category: { zh: "甜品", en: "Dessert" },
      area: { zh: "蓮洞", en: "Yeondong" },
      address: "10 Gukgijung-gil, Jeju-si",
      note: null,
      maps: "10 Gukgijung-gil, Jeju-si",
      dayHint: { zh: "適合市區晚上", en: "Good for city evening" },
    },
    {
      id: "ramen-nohyeong",
      name: { zh: "拉麵", en: "Ramen" },
      nameKo: "라멘",
      category: { zh: "拉麵", en: "Ramen" },
      area: { zh: "老衡 / 蓮洞商圈", en: "Nohyeong / Yeondong" },
      address: "제주 제주시 원노형9길 12 1층",
      note: null,
      maps: "원노형9길 12, Jeju-si",
      dayHint: { zh: "適合市區晚餐", en: "Good for city dinner" },
    },
    {
      id: "maesu-guts",
      name: { zh: "麥穗肥腸專家牛腸", en: "Maesu beef intestine specialist" },
      nameKo: "맥수곱창",
      category: { zh: "韓式內臟鍋", en: "Gopchang" },
      area: { zh: "蓮洞", en: "Yeondong" },
      address: "연동 261-28, Jeju-si",
      note: null,
      maps: "연동 261-28, Jeju-si",
      dayHint: { zh: "適合市區晚餐", en: "Good for city dinner" },
    },
    {
      id: "orrron",
      name: { zh: "orrron", en: "orrron" },
      nameKo: "오론",
      category: { zh: "咖啡 / 餐廳", en: "Café / Restaurant" },
      area: { zh: "城山 · 烏枣", en: "Seongsan · Ojo" },
      address: "394 Ojo-ri, Seongsan-eup, Seogwipo-si",
      note: null,
      maps: "394 Ojo-ri, Seongsan-eup, Seogwipo-si",
      dayHint: { zh: "適合 Day 2 城山線", en: "Fits Day 2 Seongsan leg" },
    },
    {
      id: "haenyeo-gimbap",
      name: { zh: "海女包飯", en: "Haenyeo gimbap" },
      nameKo: "해녀김밥",
      category: { zh: "輕食", en: "Light meal" },
      area: { zh: "朝天 · 咸德", en: "Jocheon · Hamdeok" },
      address: "40 Hamdeok-ro, Jocheon-eup, Jeju-si (3層 302號)",
      note: null,
      maps: "40 Hamdeok-ro, Jocheon-eup, Jeju-si",
      dayHint: null,
    },
    {
      id: "london-bagel",
      name: { zh: "倫敦貝果博物館", en: "London Bagel Museum" },
      nameKo: "런던베이글뮤지엄",
      category: { zh: "貝果", en: "Bagels" },
      area: { zh: "舊左 · 東福", en: "Gujwa · Dongbok" },
      address: "Dongbok-ro, Gujwa-eup, Jeju-si",
      note: { zh: "建議早去排隊", en: "Go early for the queue" },
      maps: "London Bagel Museum Jeju Dongbok",
      dayHint: { zh: "Day 3 未去", en: "Not visited Day 3" },
    },
    {
      id: "corn-ice-hallim",
      name: { zh: "玉米冰 + 小店逛街", en: "Corn ice cream + browsing" },
      nameKo: "옥수수아이스크림",
      category: { zh: "甜品 / 逛街", en: "Dessert / stroll" },
      area: { zh: "翰林", en: "Hallim" },
      address: "60 Gwideok 11-gil, Hallim-eup, Jeju-si",
      note: { zh: "玉米冰好吃 · 一堆好逛小東西", en: "Great corn ice cream · cute shops" },
      maps: "60 Gwideok 11-gil, Hallim-eup, Jeju-si",
      dayHint: null,
    },
    {
      id: "hugely",
      name: { zh: "hugely（橘子冰淇淋 / 海浪咖啡）", en: "hugely (orange ice / wave café)" },
      nameKo: "휴즐리",
      category: { zh: "甜品咖啡", en: "Dessert café" },
      area: { zh: "濟州市", en: "Jeju-si" },
      address: "제주 제주시 흥운길 83",
      note: { zh: "橘子冰淇淋", en: "Orange ice cream" },
      maps: "흥운길 83, Jeju-si",
      dayHint: null,
    },
    {
      id: "ox-heart",
      name: { zh: "牛心", en: "Ox heart" },
      nameKo: "우심",
      category: { zh: "餐廳", en: "Restaurant" },
      area: { zh: "老衡", en: "Nohyeong" },
      address: "제주 제주시 노형11길 18 1층",
      note: null,
      maps: "노형11길 18, Jeju-si",
      dayHint: { zh: "適合市區晚餐", en: "Good for city dinner" },
    },
    {
      id: "samdaejang",
      name: { zh: "三大將", en: "Samdaejang" },
      nameKo: "삼대장",
      category: { zh: "餐廳", en: "Restaurant" },
      area: { zh: "蓮洞", en: "Yeondong" },
      address: "연동 251-8, Jeju-si",
      note: null,
      maps: "연동 251-8, Jeju-si",
      dayHint: { zh: "適合市區晚餐", en: "Good for city dinner" },
    },
    {
      id: "muroi",
      name: { zh: "Muroi", en: "Muroi" },
      nameKo: "무로이",
      category: { zh: "咖啡 / 餐廳", en: "Café / Restaurant" },
      area: { zh: "東門路", en: "Dongmun-ro" },
      address: "Dongmun-ro, Jeju-si",
      note: null,
      maps: "Muroi Dongmun-ro Jeju",
      dayHint: { zh: "靠近七星街 / 東門", en: "Near Chilseong / Dongmun" },
    },
    {
      id: "moalboal-teuhaean",
      name: { zh: "moalboal cafe（涯月海岸）", en: "moalboal café (Aewol coast)" },
      nameKo: "모알보알",
      category: { zh: "海景咖啡", en: "Ocean café" },
      area: { zh: "涯月海岸", en: "Aewol coast" },
      address: "제주시 테우해안로 106 2층",
      note: { zh: "與舊左那間同品牌另一店", en: "Same brand, different branch" },
      maps: "테우해안로 106, Jeju-si",
      dayHint: { zh: "適合 Day 3 涯月線", en: "Fits Day 3 Aewol leg" },
    },
  ],
};
